project:
  type: book
  output-dir: docs

book:
  title: Minke Whale Report
  subtitle: The subtitle
  date: December 2022
  downloads: [pdf, docx]
  author:
  - name: Kourtney Burger
    affiliations:
      - id: swfsc-mmtd
        name: Southwest Fisheries Science Center
        department: Marine Mammal and Turtle Division
        address: 
          - 8901 La Jolla Shores Drive
          - La Jolla, California 92037
    email: kourtney.burger@noaa.gov
  - name: Shannon Rankin
    affiliations:
      - ref: swfsc-mmtd
      
  chapters:
#comment out chapters that I am not actively working on
    - index.qmd
    - text/Chapter1.qmd
    - text/conclusion.qmd
    - text/references.qmd

  site-url: https://nmfs-opensci.github.io/NOAA-tech-memo-template/
  repo-url: https://github.com/Kourtney-Burger/MinkeWhale.git
  repo-actions: [edit, source, issue]
  search: true

bibliography: [references.bib]

execute:
  echo: false
  code-overflow: wrap
  freeze: true

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
